# Generated by Django 2.2.6 on 2019-10-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('increment', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('num_room', models.SmallIntegerField()),
                ('num_build', models.SmallIntegerField()),
                ('count_places', models.SmallIntegerField()),
                ('count_resident', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id_student', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('num_year', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('department', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=300)),
            ],
        ),
    ]
