# Generated by Django 2.2.6 on 2019-10-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomsList', '0001_initial'),
        ('StudentList', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.AddField(
            model_name='students',
            name='num_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='RoomsList.Rooms'),
        ),
    ]
