# Generated by Django 2.2.6 on 2019-10-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('increment', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('num_room', models.SmallIntegerField()),
                ('num_build', models.SmallIntegerField()),
                ('count_places', models.SmallIntegerField()),
                ('count_resident', models.SmallIntegerField()),
            ],
        ),
    ]
